language: java
jdk:
 - openjdk7
    
script:
 - mvn install -DskipTests=false
 - mvn clean package assembly:assembly
 - mvn install git
 - git add "CalculadoraLib-0.0.1-SNAPSHOT-assembly.zip"
 - git commit
 - git push
