language: java
jdk:
 - openjdk7
    
script:
 - mvn install -DskipTests=false
 - mvn clean package assembly:assembly
 - gem install dpl
 - dpl --provider=releases --api-key=ba4a785b64974f2faadc0915cb572f45ef8973ee --repo=calculadoraweb --file=CalculadoraLib-0.0.1-SNAPSHOT-assembly.zip
