language: java
jdk:
 - openjdk7
    
script:
 - mvn install -DskipTests=false
 - mvn clean package assembly:assembly
 - mvn install git
 - git add "CalculadoraLib-0.0.1-SNAPSHOT-assembly.zip"
 - git commit -a -m "commit do travis para github"
 - git push https://github.com/fabiophillip/calculadoralib.git
