language: java
jdk:
 - openjdk7
    
script:
 - mvn install -DskipTests=false
 - mvn clean package assembly:assembly
 - git config --global user.email "haru_glory6@hotmail.com"
 - git config --global user.name "fabiophillip"
 - git config --global user.password "viewtiful4490"
 - git add "/home/travis/build/fabiophillip/calculadoralib/src/main/resources/CalculadoraLib-0.0.1-SNAPSHOT-assembly.zip"
 - git commit -a -m "commit do travis para github"
 - git remote add github git@github.com:fabiophillip/calculadoralib.git
